

GET https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces
###

POST https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
     "location": "Dublin POST",
    "name": "Best location"
}
###

GET https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=e0f8d09c-e1d2-4e2a-83fc-23597f68c9db

###


PUT https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=e0f8d09c-e1d2-4e2a-83fc-23597f68c9db
Content-Type: application/json

 {
    "name": "Not Best location"
 }
###

DELETE https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=123
###
