

GET https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces
###

POST https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "Paris2"
}
###

GET https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=123

###


PUT https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=123
Content-Type: application/json

{
    "location": "Paris3"
}
###

DELETE https://c7giihbfue.execute-api.us-west-1.amazonaws.com/prod/spaces?id=123
###
